### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by jedkirby** [phpwarks/website#27]
Spacecraft are now a sponsor - http://spacecraft.digital. They'll need to be added to the list of sponsors in the footer, with a bit of a description. A link to the careers site will be needed, which is; https://www.jadu.net/careers.

The logo is attached:

<img width="511" alt="spacecraft_logo" src="https://cloud.githubusercontent.com/assets/1528691/20261218/ceec477a-aa54-11e6-93f9-60772a71a705.png">

**Comment by NigelGreenway** [comment]
@jedkirby What is the content you wish to use for Spacecraft?

**Comment by NigelGreenway** [comment]
@jedkirby also, would they want any analytical reference appended to the URL?
