### ISSUE TITLE
Update main heading to PHP Warks logo.

### ISSUE THREAD

**Issue by benplummer** [phpwarks/website#28]
We need the black logo on a transparent background to use.

Might be worth generating the logo in white too for other future uses and have both variations in a few different sizes.

**Comment by jedkirby** [comment]
![main-logo-large-black](https://cloud.githubusercontent.com/assets/1528691/20264017/58ab3834-aa61-11e6-8a70-c3183b0609c0.png)
![main-logo-large-white](https://cloud.githubusercontent.com/assets/1528691/20264018/58c4c02e-aa61-11e6-81d3-bec419ab96ba.png)

**Comment by jedkirby** [comment]
@benplummer sent you the logo's via Slack.

**Comment by NigelGreenway** [comment]
![main-logo-large-black](https://cloud.githubusercontent.com/assets/2984008/20325050/ec979fb4-ab7a-11e6-8dd1-9729385cf47d.png)
![main-logo-large-white](https://cloud.githubusercontent.com/assets/2984008/20325051/ecaf3750-ab7a-11e6-977c-121d8cebd052.png)
